default:
	@cp -r dashboard motu-dashboard.wdgt
	@cp -r opera motu-opera
	@cp -r ../scripts ../images motu-dashboard.wdgt
	@cp -r ../scripts ../images motu-opera
	@zip -r motu-dashboard.wdgt.zip motu-dashboard.wdgt
	@cd motu-opera && zip -r ../motu-opera.wgt *
	@rm -rf motu-dashboard.wdgt motu-opera
